### ISSUE TITLE
Maintain show/hide state on new documents.

### ISSUE THREAD

**Issue by jerodsanto** [JulianEberius/Textmate-Minimap#8] opened 2010-02-25 14:13 UTC
The minimap is always showing on new documents, even if the current document has it hidden. Ideally new documents would inherit the show/hide state of the previous document.

**Comment by JulianEberius** [comment] 2010-02-25 14:49
I think this is another issue for the future preference pane... maybe an option like: "new documents:" -> "inherit from last document", "always on", "always off".

Thinking about that, the state should also be maintained for all documents when they are saved and reopened ...

**Comment by JulianEberius** [comment] 2010-02-28 14:43
should be fixed in release 0.6

**Comment by jaylevitt** [comment] 2010-04-21 20:44
I'm on 0.7, and the minimap appears on every document, even if the preference is set to "never" and "same as new documents".  Is that known, and if not, how can I troubleshoot? I'm on OS X 10.5.8, TextMate 1589.

**Comment by JulianEberius** [comment] 2010-04-21 21:03
Strange, I can't reproduce the bug, neither on 1510 (latest official build), nor on 1589 (cutting-edge). Everything is working fine for me (although I'm on Snow Leopard, but I can't imagine how this would make a difference), no matter what combination of settings I use.

Really don't know how to help you on this one... maybe you can offer a more detailed description?

**Comment by jaylevitt** [comment] 2010-04-22 12:07
Ah ha!  I got it.. happens on Snow Leopard too.  If you have the "Show in side bar" box checked, the minimap always appears, irrespective of the "Open/new document" preferences.

**Comment by JulianEberius** [comment] 2010-04-22 13:46
My fault, you were completely right. Had fixed this bug in my personal development version and then forgot about it. I think there will be an 0.71 bugfix release shortly ;-) The fix is already in the repository, so if you want you can clone and build with Xcode

**Comment by JulianEberius** [comment] 2010-05-03 13:01
Is fixed in 0.71 (if not, just write here again ;-) )

**Closed as completed by JulianEberius** 2010-05-03 13:01 UTC
