### ISSUE TITLE
Deadlock during drawing

### ISSUE THREAD

**Issue by dwt** [JulianEberius/Textmate-Minimap#19] opened 2010-05-02 19:55 UTC
I've reported this bug first on textmates bugtracker at http://ticket.macromates.com/show?ticket_id=57E629A7

See there for details and stacktraces. :-)

**Comment by JulianEberius** [comment] 2010-05-03 12:55
Hi!

Thanks for reporting this issue. I looked into it, and have an idea from looking at the trace. Sadly, I'm unable to reproduce the deadlock (so I dont' know if I fix it when I apply the idea ^^). No matter how much I switch tabs, open/close new ones, etc I never get the deadlock.

Do you have the newest version of Minimap and Textmate?
Is there anything special you are doing when the deadlock happens (opening/closing windows, tabs etc) ? 

Thanks again,
Julian

**Comment by dwt** [comment] 2010-05-09 19:43
Hm, not that I can say so. I haven't seen this in the last days, so I guess  one of the last updates may have fixed this. I'll add to this bug if I see it again.

**Closed as completed** 2011-08-04 21:37 UTC
